// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mode

import (
	"context"
	"os"
	"os/exec"
	"sync"
)

// Ensure, that ExecutorMock does implement Executor.
// If this is not the case, regenerate this file with moq.
var _ Executor = &ExecutorMock{}

// ExecutorMock is a mock implementation of Executor.
//
//	func TestSomethingThatUsesExecutor(t *testing.T) {
//
//		// make and configure a mocked Executor
//		mockedExecutor := &ExecutorMock{
//			LookPathFunc: func(file string) (string, error) {
//				panic("mock out the LookPath method")
//			},
//			OutputFunc: func(cmd *exec.Cmd) ([]byte, error) {
//				panic("mock out the Output method")
//			},
//			ReadDirFunc: func(name string) ([]os.DirEntry, error) {
//				panic("mock out the ReadDir method")
//			},
//			StatFunc: func(name string) (os.FileInfo, error) {
//				panic("mock out the Stat method")
//			},
//		}
//
//		// use mockedExecutor in code that requires Executor
//		// and then make assertions.
//
//	}
type ExecutorMock struct {
	// LookPathFunc mocks the LookPath method.
	LookPathFunc func(file string) (string, error)

	// OutputFunc mocks the Output method.
	OutputFunc func(cmd *exec.Cmd) ([]byte, error)

	// ReadDirFunc mocks the ReadDir method.
	ReadDirFunc func(name string) ([]os.DirEntry, error)

	// StatFunc mocks the Stat method.
	StatFunc func(name string) (os.FileInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// LookPath holds details about calls to the LookPath method.
		LookPath []struct {
			// File is the file argument value.
			File string
		}
		// Output holds details about calls to the Output method.
		Output []struct {
			// Cmd is the cmd argument value.
			Cmd *exec.Cmd
		}
		// ReadDir holds details about calls to the ReadDir method.
		ReadDir []struct {
			// Name is the name argument value.
			Name string
		}
		// Stat holds details about calls to the Stat method.
		Stat []struct {
			// Name is the name argument value.
			Name string
		}
	}
	lockLookPath sync.RWMutex
	lockOutput   sync.RWMutex
	lockReadDir  sync.RWMutex
	lockStat     sync.RWMutex
}

// LookPath calls LookPathFunc.
func (mock *ExecutorMock) LookPath(file string) (string, error) {
	if mock.LookPathFunc == nil {
		panic("ExecutorMock.LookPathFunc: method is nil but Executor.LookPath was just called")
	}
	callInfo := struct {
		File string
	}{
		File: file,
	}
	mock.lockLookPath.Lock()
	mock.calls.LookPath = append(mock.calls.LookPath, callInfo)
	mock.lockLookPath.Unlock()
	return mock.LookPathFunc(file)
}

// LookPathCalls gets all the calls that were made to LookPath.
// Check the length with:
//
//	len(mockedExecutor.LookPathCalls())
func (mock *ExecutorMock) LookPathCalls() []struct {
	File string
} {
	var calls []struct {
		File string
	}
	mock.lockLookPath.RLock()
	calls = mock.calls.LookPath
	mock.lockLookPath.RUnlock()
	return calls
}

// Output calls OutputFunc.
func (mock *ExecutorMock) Output(cmd *exec.Cmd) ([]byte, error) {
	if mock.OutputFunc == nil {
		panic("ExecutorMock.OutputFunc: method is nil but Executor.Output was just called")
	}
	callInfo := struct {
		Cmd *exec.Cmd
	}{
		Cmd: cmd,
	}
	mock.lockOutput.Lock()
	mock.calls.Output = append(mock.calls.Output, callInfo)
	mock.lockOutput.Unlock()
	return mock.OutputFunc(cmd)
}

// OutputCalls gets all the calls that were made to Output.
// Check the length with:
//
//	len(mockedExecutor.OutputCalls())
func (mock *ExecutorMock) OutputCalls() []struct {
	Cmd *exec.Cmd
} {
	var calls []struct {
		Cmd *exec.Cmd
	}
	mock.lockOutput.RLock()
	calls = mock.calls.Output
	mock.lockOutput.RUnlock()
	return calls
}

// ReadDir calls ReadDirFunc.
func (mock *ExecutorMock) ReadDir(name string) ([]os.DirEntry, error) {
	if mock.ReadDirFunc == nil {
		panic("ExecutorMock.ReadDirFunc: method is nil but Executor.ReadDir was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockReadDir.Lock()
	mock.calls.ReadDir = append(mock.calls.ReadDir, callInfo)
	mock.lockReadDir.Unlock()
	return mock.ReadDirFunc(name)
}

// ReadDirCalls gets all the calls that were made to ReadDir.
// Check the length with:
//
//	len(mockedExecutor.ReadDirCalls())
func (mock *ExecutorMock) ReadDirCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockReadDir.RLock()
	calls = mock.calls.ReadDir
	mock.lockReadDir.RUnlock()
	return calls
}

// Stat calls StatFunc.
func (mock *ExecutorMock) Stat(name string) (os.FileInfo, error) {
	if mock.StatFunc == nil {
		panic("ExecutorMock.StatFunc: method is nil but Executor.Stat was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockStat.Lock()
	mock.calls.Stat = append(mock.calls.Stat, callInfo)
	mock.lockStat.Unlock()
	return mock.StatFunc(name)
}

// StatCalls gets all the calls that were made to Stat.
// Check the length with:
//
//	len(mockedExecutor.StatCalls())
func (mock *ExecutorMock) StatCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockStat.RLock()
	calls = mock.calls.Stat
	mock.lockStat.RUnlock()
	return calls
}

// Ensure, that ModeProviderMock does implement ModeProvider.
// If this is not the case, regenerate this file with moq.
var _ ModeProvider = &ModeProviderMock{}

// ModeProviderMock is a mock implementation of ModeProvider.
//
//	func TestSomethingThatUsesModeProvider(t *testing.T) {
//
//		// make and configure a mocked ModeProvider
//		mockedModeProvider := &ModeProviderMock{
//			DetectFunc: func(ctx context.Context, req DetectRequest) (bool, error) {
//				panic("mock out the Detect method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			PlanFunc: func(ctx context.Context, req PlanRequest) (PlanResult, error) {
//				panic("mock out the Plan method")
//			},
//		}
//
//		// use mockedModeProvider in code that requires ModeProvider
//		// and then make assertions.
//
//	}
type ModeProviderMock struct {
	// DetectFunc mocks the Detect method.
	DetectFunc func(ctx context.Context, req DetectRequest) (bool, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// PlanFunc mocks the Plan method.
	PlanFunc func(ctx context.Context, req PlanRequest) (PlanResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Detect holds details about calls to the Detect method.
		Detect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req DetectRequest
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Plan holds details about calls to the Plan method.
		Plan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req PlanRequest
		}
	}
	lockDetect sync.RWMutex
	lockName   sync.RWMutex
	lockPlan   sync.RWMutex
}

// Detect calls DetectFunc.
func (mock *ModeProviderMock) Detect(ctx context.Context, req DetectRequest) (bool, error) {
	if mock.DetectFunc == nil {
		panic("ModeProviderMock.DetectFunc: method is nil but ModeProvider.Detect was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req DetectRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockDetect.Lock()
	mock.calls.Detect = append(mock.calls.Detect, callInfo)
	mock.lockDetect.Unlock()
	return mock.DetectFunc(ctx, req)
}

// DetectCalls gets all the calls that were made to Detect.
// Check the length with:
//
//	len(mockedModeProvider.DetectCalls())
func (mock *ModeProviderMock) DetectCalls() []struct {
	Ctx context.Context
	Req DetectRequest
} {
	var calls []struct {
		Ctx context.Context
		Req DetectRequest
	}
	mock.lockDetect.RLock()
	calls = mock.calls.Detect
	mock.lockDetect.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *ModeProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("ModeProviderMock.NameFunc: method is nil but ModeProvider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedModeProvider.NameCalls())
func (mock *ModeProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Plan calls PlanFunc.
func (mock *ModeProviderMock) Plan(ctx context.Context, req PlanRequest) (PlanResult, error) {
	if mock.PlanFunc == nil {
		panic("ModeProviderMock.PlanFunc: method is nil but ModeProvider.Plan was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req PlanRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockPlan.Lock()
	mock.calls.Plan = append(mock.calls.Plan, callInfo)
	mock.lockPlan.Unlock()
	return mock.PlanFunc(ctx, req)
}

// PlanCalls gets all the calls that were made to Plan.
// Check the length with:
//
//	len(mockedModeProvider.PlanCalls())
func (mock *ModeProviderMock) PlanCalls() []struct {
	Ctx context.Context
	Req PlanRequest
} {
	var calls []struct {
		Ctx context.Context
		Req PlanRequest
	}
	mock.lockPlan.RLock()
	calls = mock.calls.Plan
	mock.lockPlan.RUnlock()
	return calls
}
